* Store
一个受[[https://couchdb.apache.org][CouchDB]]启发的Web友好的自托管ad-hoc微服务.
提供基于 HTTP 的键值对JSON文档数据库,
带有基于token和名单的访问控制策略,
支持JSON Schema.

** Quickstart
#+BEGIN_SRC sh
docker run --detach --log 8080:8080 blackglory/store

curl http://localhost:8080/store/my-db/items/my-doc-id \
  --request PUT \
  --header 'Content-Type: application/json' \
  --data '{ "message": "Hello World" }'

curl http://localhost:8080/store/my-db/items/my-doc-id
# { "message": "Hello World" }

curl http://localhost:8080/store/my-db/items/my-doc-id --request DELETE

curl http://localhost:8080/store/my-db/items/my-doc-id
# 404 Not Found
#+END_SRC

** Install
*** 从源代码运行
可以使用环境变量 =STORE_HOST= 和 =STORE_PORT= 决定服务器监听的地址和端口, 默认值为localhost和8080.

#+BEGIN_SRC sh
git clone https://github.com/BlackGlory/store
cd log
yarn install
yarn build
yarn --silent start
#+END_SRC

*** Docker
#+BEGIN_SRC sh
docker run \
  --detach \
  --publish 8080:8080 \
  blackglory/store
#+END_SRC

**** 从源代码构建
#+BEGIN_SRC sh
git clone https://github.com/BlackGlory/store
cd store
yarn install
yarn docker:build
#+END_SRC

**** Recipes
***** 公开服务器
****** docker-compose.yml
#+BEGIN_SRC yaml
version: '3.8'

services:
  store:
    image: 'blackglory/store'
    restart: always
    volumes:
      - 'store-data:/data'
    ports:
      - '8080:8080'

volumes:
  store-data:
#+END_SRC

***** 私人服务器
****** docker-compose.yml
#+BEGIN_SRC yaml
version: '3.8'

services:
  store:
    image: 'blackglory/store'
    restart: always
    environment:
      - STORE_ADMIN_PASSWORD=password
      - STORE_TOKEN_BASED_ACCESS_CONTROL=true
      - STORE_WRITE_TOKEN_REQUIRED=true
      - STORE_READ_TOKEN_REQUIRED=true
      - STORE_DELETE_TOKEN_REQUIRED=true
    volumes:
      - 'store-data:/data'
    ports:
      - '8080:8080'

volumes:
  store-data:
#+END_SRC
** API
*** Public
所有API中的store和item的id都需要满足此正则表达式: =^[a-zA-Z0-9\.\-_]{1,256}$=

**** set
=PUT /store/<db>/items/<id>=

在指定的存储器(db)里, 插入/更新特定JSON文档(id).

只接受带有 =Content-Type: application/json= 的请求,
当payload不是合法的JSON时, 将返回400.

成功创建文档时返回201, 正文为空, 响应头 =ETag= 里包含新的revision.
成功更新文档时返回204, 正文为空, 响应头 =ETag= 里包含新的revision.
revision 是一个由服务器计算出的值, 该值可被用于基于revision的缓存和乐观并发策略.

可以使用 =If-Match= 发送带有revision的请求, 这可以在更新时启用乐观并发策略,
当revision与服务器的文档不匹配时返回412.

***** Example
****** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header 'Content-Type: application/json' \
  --data "$DOC" \
  "http://localhost:8080/store/$db/items/$id"
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch(`http://localhost:8080/store/${db}/items/${id}`, {
  method: 'PUT'
, headers: {
    'Content-Type': 'application/json'
  }
, body: JSON.stringify(doc)
})
#+END_SRC

**** has
=HEAD /store/<db>/items/<id>=

检测文档是否存在, 返回200或404.

响应头 =ETag= 里包含文档当前的revision.

可以使用 =If-None-Match= 发送带有revision的请求, 这可以启用基于revision的缓存,
如果revision与服务器的文档一致, 将返回304, 否则返回200或404.

***** Example
****** curl
#+BEGIN_SRC sh
curl \
  --request HEAD \
  "http://localhost:8080/store/$db/items/$id"
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch(`http://localhost:8080/store/${db}/items/${id}`, {
  method: 'HEAD'
})
#+END_SRC

**** get
=GET /store/<db>/items/<id>=

获取JSON文档, 返回200或404.

响应头 =ETag= 里包含文档当前的revision.

可以使用 =If-None-Match= 发送带有revision的请求, 这可以启用基于revision的缓存,
如果revision与服务器的文档一致, 将返回304, 否则返回200或404.

***** Example
****** curl
#+BEGIN_SRC sh
curl "http://localhost:8080/store/$db/items/$id"
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch(`http://localhost:8080/store/${db}/items/${id}`)
#+END_SRC

**** list
=GET /store/<db>/items=

获取所有项目的id, 返回 =string[]=.

如果返回的内容很多, 客户端可能需要JSON流([[https://en.wikipedia.org/wiki/JSON_streaming][JSON streaming]]), 因此也支持返回[[https://github.com/ndjson/ndjson-spec][ndjson]]格式,
只需要在请求头中设置 =Accept: application/x-ndjson=.

***** Example
****** curl
#+BEGIN_SRC sh
curl "http://localhost:8080/store/$db/items"
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch(`http://localhost:8080/store/${db}/items`).then(res => res.json())
#+END_SRC

**** delete
=DELETE /store/<db>/items/<id>=

删除特定JSON文档, 返回204或404.

可以使用 =If-Match= 发送带有revision的请求, 这可以防止幻影删除,
当revision与服务器的文档不匹配时返回412.

***** Example
****** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  "http://localhost:8080/store/$db/items/$id"
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch(`http://localhost:8080/store/${db}/items/${id}`, {
  method: 'DELETE'
})
#+END_SRC

**** 统计信息
=GET /stats=

输出JSON:
#+BEGIN_SRC ts
{
  memoryUsage: NodeJS.MemoryUsage
  cpuUsage: NodeJS.CpuUsage
  resourceUsage: NodeJS.ResourceUsage
}
#+END_SRC

***** Example
****** curl
#+BEGIN_SRC sh
curl 'http://localhost:8080/stats'
#+END_SRC

****** JavaScript
#+BEGIN_SRC js
await fetch('http://localhost:8080/stats').then(res => res.json())
#+END_SRC

*** Private
**** JSON Schema验证
通过环境变量 =STORE_DEFAULT_JSON_SCHEMA= 可设置默认的JSON Schema.

***** 为Store单独设置JSON Schema
可单独为store设置JSON Schema, 被设置的store将仅接受 =Content-Type: application/json= 请求.

****** 获取所有具有JSON Schema的StoreId
=GET /api/store-with-json-schema=

获取所有具有JSON Schema的StoreId, 返回由JSON表示的字符串数组 =string[]=.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store-with-json-schema"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch('http://localhost:8080/api/store-with-json-schema', {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

****** 获取JSON Schema
=GET /api/store/<id>/json-schema=

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/json-schema"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/json-schema`, {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

****** 设置JSON Schema
=PUT /api/store/<id>/json-schema=

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  --header "Content-Type: application/json" \
  --data "$JSON_SCHEMA" \
  "http://localhost:8080/api/store/$id/jsonschema"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/json-schema`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
    'Content-Type': 'application/json'
  }
, body: JSON.stringify(jsonSchema)
})
#+END_SRC

****** 移除JSON Schema
=DELETE /api/store/<id>/json-schema=

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/json-schema"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/json-schema`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

**** Revision策略
设置环境变量 =STORE_UPDATE_REVISION_REQUIRED=true= 可强制要求客户端在发出更新请求时提供 =If-Match= 请求头, 默认为 =false=.
设置环境变量 =STORE_DELETE_REVISION_REQUIRED=true= 可强制要求客户端在发出删除请求时提供 =If-Match= 请求头, 默认为 =false=.

可单独为特定store设置策略以覆盖默认值.

***** 获取所有具有revision策略的Store id
=GET /api/store-with-revision-policies=

返回由JSON表示的字符串数组 =string[]=.

****** Example 
******* curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store-with-revision-policies"
#+END_SRC

******* fetch
#+BEGIN_SRC js
await fetch('http://localhost:8080/api/store-with-revision-policies', {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

***** 获取特定store的revision策略
=GET /api/store/<id>/revision-policies=

返回JSON:
#+BEGIN_SRC ts
{
  updateRevisionRequired: boolean | null
  deleteRevisionRequired: boolean | null
}
#+END_SRC
=null= 代表沿用相关默认值.

****** Example
******* curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/revision-policies"
#+END_SRC

******* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/revision-policies`, {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

***** 设置revision策略
=PUT /api/store/<id>/revision-policies/update-revision-required=
=PUT /api/store/<id>/revision-policies/delete-revision-required=

Payload必须是一个布尔值.

****** Example
******* curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  --header "Content-Type: application/json" \
  --data "$UPDATE_REVISION_RQUIRED" \
  "http://localhost:8080/api/store/$id/revision-policies/update-revision-required"
#+END_SRC

******* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/revision-policies/update-revision-required`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  , 'Content-Type': 'application/json'
  }
, body: JSON.stringify(updateRevisionRequired)
})
#+END_SRC

***** 移除revision策略
=DELETE /api/store/<id>/revision-policies/update-revision-required=
=DELETE /api/store/<id>/revision-policies/delete-revision-required=

****** Example
******* curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/revision-policies/update-revision-required"
#+END_SRC

******* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/revision-policies/update-revision-required`, {
  method: 'DELETE'
})
#+END_SRC

**** 访问控制
Store提供两种可以同时启用的访问控制策略.

所有访问控制API都使用基于口令的Bearer Token Authentication.
口令需通过环境变量 =STORE_ADMIN_PASSWORD= 进行设置.

访问控制规则是通过[[https://www.sqlite.org/wal.html][WAL模式]]的SQLite3持久化的, 开启访问控制后,
服务器的吞吐量和响应速度会受到硬盘性能的影响.

已经打开的连接不会受到新的访问控制规则的影响.

***** 基于名单的访问控制
通过设置环境变量 =STORE_LIST_BASED_ACCESS_CONTROL= 开启基于名单的访问控制:
- =whitelist=
  启用基于Store白名单的访问控制, 只有在名单内的Store允许被访问.
- =blacklist=
  启用基于Store黑名单的访问控制, 只有在名单外的Store允许被访问.

****** 黑名单
******* 获取黑名单
=GET /api/blacklist=

获取位于黑名单中的所有StoreId, 返回JSON表示的字符串数组 =string[]=.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/blacklist"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch('http://localhost:8080/api/blacklist', {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

******* 添加黑名单
=PUT /api/blacklist/<id>=

将特定Store加入黑名单.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/blacklist/$id"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/blacklist/${id}`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

******* 移除黑名单
=DELETE /api/blacklist/<id>=

将特定Store从黑名单中移除.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/blacklist/$id"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/blacklist/${id}`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 白名单
******* 获取白名单
=GET /api/whitelist=

获取位于黑名单中的所有StoreId, 返回JSON表示的字符串数组 =string[]=.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIM_PASSWORD" \
  "http://localhost:8080/api/whitelist"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch('http://localhost:8080/api/whitelist', {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

******* 添加白名单
=PUT /api/whitelist/<id>=

将特定Store加入白名单.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/whitelist/$id"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/whitelist/${id}`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

******* 移除白名单
=DELETE /api/whitelist/<id>=

将特定Store从白名单中移除.

******** Example
********* curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/whitelist/$id"
#+END_SRC

********* fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/whitelist/${id}`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

***** 基于token的访问控制
对token的要求: =^[a-zA-Z0-9\.\-_]{1,256}$=

通过设置环境变量 =STORE_TOKEN_BASED_ACCESS_CONTROL=true= 开启基于token的访问控制.

基于token的访问控制将根据消息队列的token access policy决定其访问规则.
可通过环境变量 =STORE_WRITE_TOKEN_REQUIRED=, =STORE_READ_TOKEN_REQUIRED=,
=STORE_DELETE_TOKEN_REQUIRED= 设置相关默认值,
未设置情况下为 =false=.

一个消息队列可以有多个token, 每个token可以单独设置write和read权限, 不同消息队列的token不共用.

基于token的访问控制作出了以下假设
- token的传输过程是安全的
- token难以被猜测
- token的意外泄露可以被迅速处理

****** 获取所有具有token策略的频道id
=GET /api/store-with-token-policies=

获取所有具有token策略的频道id, 返回由JSON表示的字符串数组 =string[]=.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store-with-token-policies"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch('http://localhost:8080/api/store-with-token-policies')
#+END_SRC

****** 获取特定频道的token策略
=GET /api/store/<id>/token-policies=

返回JSON:
#+BEGIN_SRC ts
{
  writeTokenRequired: boolean | null
  readTokenRequired: boolean | null
  deleteTokenRequired: boolean | null
}
#+END_SRC
=null= 代表沿用相关默认值.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/token-policies"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fethc(`http://localhost:8080/api/store/${id}/token-policies`, {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

****** 设置token策略
=PUT /api/store/<id>/token-policies/write-token-required=
=PUT /api/store/<id>/token-policies/read-token-required=
=PUT /api/store/<id>/token-policies/delete-token-required=

Payload必须是一个布尔值.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  --header "Content-Type: application/json" \
  --data "$WRITE_TOKEN_REQUIRED" \
  "http://localhost:8080/api/store/$id/token-policies/write-token-required"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/token-policies/write-token-required`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  , 'Content-Type': 'application/json'
  }
, body: JSON.stringify(writeTokenRequired)
})
#+END_SRC

****** 移除token策略
=DELETE /api/store/<id>/token-policies/write-token-required=
=DELETE /api/store/<id>/token-policies/read-token-required=
=DELETE /api/store/<id>/token-policies/delete-token-required=

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/token-policies/write-token-required"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/token-policies/write-token-required`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 获取所有具有token的StoreId
=GET /api/store-with-tokens=

获取所有具有token的StoreId, 返回由JSON表示的字符串数组`string[]`

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store-with-tokens"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store-with-tokens`, {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

****** 获取特定Store的所有token信息
=GET /api/store/<id>/tokens=

获取特定Store的所有token信息, 返回JSON表示的token信息数组
=Array<{ token: string, write: boolean, read: boolean, delete: boolean }>=.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens`, {
  headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
}).then(res => res.json())
#+END_SRC

****** 为特定Store的token设置write权限
=PUT /api/store/<id>/tokens/<token>/write=

添加/更新token, 为token设置write权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/log"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/$token/log`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 取消特定Store的token的write权限
=DELETE /api/store/<id>/tokens/<token>/write=

取消token的read权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/write"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/${token}/write`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 为特定Store的token设置read权限
=PUT /api/store/<id>/tokens/<token>/read=

添加/更新token, 为token设置read权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/read"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/$token/read`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 取消特定Store的token的read权限
=DELETE /api/store/<id>/tokens/<token>/read=

取消token的read权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/read"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/${token}/read`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 为特定Store的token设置delete权限
=PUT /api/store/<id>/tokens/<token>/delete=

添加/更新token, 为token设置delete权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request PUT \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/delete"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/$token/delete`, {
  method: 'PUT'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

****** 取消特定Store的token的delete权限
=DELETE /api/store/<id>/tokens/<token>/delete=

取消token的delete权限.

******* Example
******** curl
#+BEGIN_SRC sh
curl \
  --request DELETE \
  --header "Authorization: Bearer $ADMIN_PASSWORD" \
  "http://localhost:8080/api/store/$id/tokens/$token/delete"
#+END_SRC

******** fetch
#+BEGIN_SRC js
await fetch(`http://localhost:8080/api/store/${id}/tokens/${token}/delete`, {
  method: 'DELETE'
, headers: {
    'Authorization': `Bearer ${adminPassword}`
  }
})
#+END_SRC

** HTTP/2
Store支持HTTP/2, 以多路复用反向代理时的连接, 可通过设置环境变量 =STORE_HTTP2=true= 开启.

此HTTP/2支持不提供从HTTP/1.1自动升级的功能, 亦不提供HTTPS.
因此, 在本地curl里进行测试时, 需要开启 =--http2-prior-knowledge= 选项.

** 限制Payload大小
设置环境变量 =STORE_PAYLOAD_LIMIT= 可限制服务接受的单个请求的Payload字节数, 默认值为1048576(1MB).

设置环境变量 =STORE_WRITE_PAYLOAD_LIMIT= 可限制write接受的单个请求的Payload字节数,
默认值继承自 =STORE_PAYLOAD_LIMIT=.

** 用例展柜
*** 作为锁
可以将Store的一个文档作为锁来使用.
首先将该文档设置为仅可通过token访问, 接着添加只有read, write和delete权限的token.
开启该文档的强制ETag特性.

**** 锁的获取
每个客户端都应该有一个uuid,
根据此uuid创建JSON文档: ={ "uuid": "YOUR_UUID" }=.

用has在store上获取锁位置的文档内容, 若返回404, 则说明未锁定, 尝试获取锁.
若返回200, 则检查文档内的uuid是否与自身一致, 如果一致, 则释放锁,
这可能是由该客户端获取, 但崩溃后未被释放的死锁,
如果不一致, 则定期轮询等待锁被其他客户端释放.

用set存储JSON文档来尝试获取锁, 如果返回201, 则锁获取成功, 如果返回412, 则说明锁被其他客户端抢先获取.
如果set时出现网络异常, 则应该用get检查文档的uuid, 如果和自身一致, 则说明锁获取成功.

**** 锁的释放
通过delete相应的文档, 可实现锁的释放.
